### ISSUE TITLE
Mojo::Server::Threaded 0.16: t/02-elzar.t seems to fail on Mojolicious 8.37

### ISSUE THREAD

**Issue by twata1** [tomk3003/mojo-server-threaded#3]
Hi,

It seems to me that t/02-elzar.t fails on Mojolicious 8.37 .

```
C:\home\sunlight\Mojo-Server-Threaded-0.16>gmake test
"C:\Strawberry\perl\bin\perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib\lib', 'blib\arch')" t/*.t
t/01-threaded.t .. ok
t/02-elzar.t ..... 1/? # running >>"C:\Strawberry\perl\bin\perl.exe" "C:/home/sunlight/Mojo-Server-Threaded-0.16/t/../script/elzar" "elzez2yP\myapp.pl" <<
# wait for server startup, 1
t/02-elzar.t ..... 17/? # running >>"C:\Strawberry\perl\bin\perl.exe" "C:/home/sunlight/Mojo-Server-Threaded-0.16/t/../script/elzar" "elzez2yP\myapp.pl" <<
# wait for upgrade to fail, 1
# wait for upgrade to fail, 2
[2020-04-26 20:06:39.70454] [1640] [info] sending 'DEPLOY' to port 60935
# wait for upgrade to fail, 3
Can't load application from file "C:\home\sunlight\Mojo-Server-Threaded-0.16\elzez2yP\myapp.pl": Died at C:\home\sunlight\Mojo-Server-Threaded-0.16\elzez2yP\myapp.pl line 3.
Compilation failed in require at (eval 102) line 1.
# wait for upgrade to fail, 4
# wait for upgrade to fail, 5
# wait for upgrade to fail, 6
# wait for upgrade to fail, 7
# wait for upgrade to fail, 8
# wait for upgrade to fail, 9
# wait for upgrade to fail, 10
# wait for upgrade to fail, 11
# wait for upgrade to fail, 12
# wait for upgrade to fail, 13
t/02-elzar.t ..... 37/?
#   Failed test 'connection was kept alive'
#   at t/02-elzar.t line 191.

#   Failed test 'connection was kept alive'
#   at t/02-elzar.t line 199.
# running >>"C:\Strawberry\perl\bin\perl.exe" "C:/home/sunlight/Mojo-Server-Threaded-0.16/t/../script/elzar" "elzez2yP\myapp.pl" <<
# wait for hot deploy to finish, 1
# wait for hot deploy to finish, 2
# wait for hot deploy to finish, 3
t/02-elzar.t ..... 63/? # running >>"C:\Strawberry\perl\bin\perl.exe" "C:/home/sunlight/Mojo-Server-Threaded-0.16/t/../script/elzar" "elzez2yP\myapp.pl" -s<<
# wait for server shutdown, 1
# wait for server shutdown, 2
t/02-elzar.t ..... 74/? # Looks like you failed 2 tests of 76.
t/02-elzar.t ..... Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/76 subtests

Test Summary Report
-------------------
t/02-elzar.t   (Wstat: 512 Tests: 76 Failed: 2)
  Failed tests:  39, 44
  Non-zero exit status: 2
Files=2, Tests=115, 35 wallclock secs ( 0.08 usr +  0.06 sys =  0.14 CPU)
Result: FAIL
Failed 1/2 test programs. 2/115 subtests failed.
gmake: *** [Makefile:891: test_dynamic] Error 2

C:\home\sunlight\Mojo-Server-Threaded-0.16>module-version Mojolicious

The version of Mojolicious in C:\home\sunlight\perl5\lib\perl5 is 8.37


C:\home\sunlight\Mojo-Server-Threaded-0.16>
```

[Environment]
Windows 8.1 (64bit)
Strawberry Perl 5.30.0 (64bit)

Thank you,

**Comment by tomk3003** [comment]
8.37 changed timeouts that effected the timings for the hot deploy mechanism.
There was a bug in Elzar.pm, where a failed upgrade was only detected after the upgrade timeout kicked in. 
I fixed this. Now the timing should not be an issue at all. I will be releasing 0.17 soon.

**Comment by twata1** [comment]
Thank you for your help.
However, it seems to me that t/02-elzar.t still fails.

```
C:\home\sunlight\Mojo-Server-Threaded-0.17>gmake test
"C:\Strawberry\perl\bin\perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib\lib', 'blib\arch')" t/*.t
t/01-threaded.t .. ok
t/02-elzar.t ..... 1/? # running >>"C:\Strawberry\perl\bin\perl.exe" "C:/home/sunlight/Mojo-Server-Threaded-0.17/t/../script/elzar" "elzgDBpU\myapp.pl" <<
# wait for server startup, 1
t/02-elzar.t ..... 17/? # running >>"C:\Strawberry\perl\bin\perl.exe" "C:/home/sunlight/Mojo-Server-Threaded-0.17/t/../script/elzar" "elzgDBpU\myapp.pl" <<
# wait for upgrade to fail, 1
# wait for upgrade to fail, 2
[2020-04-29 10:50:59.51865] [6540] [info] sending 'DEPLOY' to port 64120
# wait for upgrade to fail, 3
Can't load application from file "C:\home\sunlight\Mojo-Server-Threaded-0.17\elzgDBpU\myapp.pl": Died at C:\home\sunlight\Mojo-Server-Threaded-0.17\elzgDBpU\myapp.pl line 3.
Compilation failed in require at (eval 102) line 1.
# wait for upgrade to fail, 4
t/02-elzar.t ..... 37/?
#   Failed test 'connection was kept alive'
#   at t/02-elzar.t line 191.

#   Failed test 'connection was kept alive'
#   at t/02-elzar.t line 199.
# running >>"C:\Strawberry\perl\bin\perl.exe" "C:/home/sunlight/Mojo-Server-Threaded-0.17/t/../script/elzar" "elzgDBpU\myapp.pl" <<
# wait for hot deploy to finish, 1
# wait for hot deploy to finish, 2
# wait for hot deploy to finish, 3
t/02-elzar.t ..... 63/? # running >>"C:\Strawberry\perl\bin\perl.exe" "C:/home/sunlight/Mojo-Server-Threaded-0.17/t/../script/elzar" "elzgDBpU\myapp.pl" -s<<
# wait for server shutdown, 1
# wait for server shutdown, 2
t/02-elzar.t ..... 74/? # Looks like you failed 2 tests of 76.
t/02-elzar.t ..... Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/76 subtests

Test Summary Report
-------------------
t/02-elzar.t   (Wstat: 512 Tests: 76 Failed: 2)
  Failed tests:  39, 44
  Non-zero exit status: 2
Files=2, Tests=115, 26 wallclock secs ( 0.08 usr +  0.00 sys =  0.08 CPU)
Result: FAIL
Failed 1/2 test programs. 2/115 subtests failed.
gmake: *** [Makefile:891: test_dynamic] Error 2

C:\home\sunlight\Mojo-Server-Threaded-0.17>
C:\home\sunlight\Mojo-Server-Threaded-0.17>module-version Mojolicious

The version of Mojolicious in C:\home\sunlight\perl5\lib\perl5 is 8.37


C:\home\sunlight\Mojo-Server-Threaded-0.17>
```

**Comment by tomk3003** [comment]
I "fixed" it by skipping these tests for user installs.

**Comment by twata1** [comment]
Thank you,

What I can say is that I hope someday these tests will pass without skipping.

Thank you again.

**Comment by tomk3003** [comment]
I don't know why the tests fail. I could not reproduce this. My appveyor tests and the local tests always succeed. Since I have no control over the user's environment and these are timing related tests, I am happy to skip them. This most likely will have no impact on functionality.

**Comment by twata1** [comment]
I have noticed that t/02-elzar.t passes by setting the environment variable as follows:

set MOJO_KEEP_ALIVE_TIMEOUT=0

I tested on Mojolicious 8.52 and Mojo::Server::Threaded 0.18 .
